"""
generate_rules.py
-------------------------
This file generates Association Rules from the Frequent Itemsets produced
by the Apriori algorithm.

What this file does:
1. Takes the frequent_itemsets DataFrame.
2. Generates association rules using metrics:
      - support
      - confidence
      - lift
3. Filters weak rules.
4. Saves final rule sets into the output folder.

Auto-generated output files:
- output/association_rules.csv
- output/top_rules.csv
"""

import pandas as pd
from mlxtend.frequent_patterns import association_rules


def generate_rules(frequent_itemsets, min_confidence=0.3, min_lift=1.0):
    """
    Generates association rules from frequent itemsets.

    Args:
        frequent_itemsets (DataFrame): Itemsets generated by Apriori.
        min_confidence (float): Minimum confidence threshold.
        min_lift (float): Minimum lift threshold.

    Returns:
        DataFrame: Cleaned rules sorted by highest lift.
    """

    print("[INFO] Generating association rules...")
    print(f"[INFO] Confidence threshold: {min_confidence}")
    print(f"[INFO] Lift threshold: {min_lift}")

    # ----------------------------------------------------
    # STEP 1: Create rules using mlxtend's built-in function
    # ----------------------------------------------------
    # 'metric="confidence"' means rules will be filtered first by confidence.
    # 'min_threshold=min_confidence' means minimum acceptable confidence.
    rules = association_rules(
        frequent_itemsets,
        metric="confidence",
        min_threshold=min_confidence
    )

    print(f"[INFO] Total raw rules generated: {len(rules)}")

    # ----------------------------------------------------
    # STEP 2: Filter rules based on lift
    # ----------------------------------------------------
    # Lift measures how strong the relationship is compared to random chance.
    rules = rules[rules["lift"] >= min_lift]

    print(f"[INFO] Rules remaining after lift filtering: {len(rules)}")

    # ----------------------------------------------------
    # STEP 3: Sort rules by lift (strongest patterns first)
    # ----------------------------------------------------
    rules = rules.sort_values(by="lift", ascending=False)

    # ----------------------------------------------------
    # STEP 4: Save all rules to file
    # ----------------------------------------------------
    all_rules_path = "output/association_rules.csv"
    rules.to_csv(all_rules_path, index=False)
    print(f"[INFO] All rules saved to: {all_rules_path}")

    # ----------------------------------------------------
    # STEP 5: Save top 20 rules separately for quick review
    # ----------------------------------------------------
    top_rules = rules.head(20)
    top_rules_path = "output/top_rules.csv"
    top_rules.to_csv(top_rules_path, index=False)
    print(f"[INFO] Top 20 rules saved to: {top_rules_path}")

    return rules


# ------------------------------------------------------------
# TEST MODE (Runs when executing this file directly)
# ------------------------------------------------------------
if __name__ == "__main__":
    print("[TEST] Running generate_rules.py directly...")

    # Importing other modules for test run
    from load_data import load_raw_data
    from preprocess import preprocess_data
    from apriori_model import create_basket_format, run_apriori

    # Load + preprocess dataset
    df_raw = load_raw_data()
    df_clean = preprocess_data(df_raw)

    # Create basket format
    basket = create_basket_format(df_clean)

    # Run Apriori
    frequent_itemsets = run_apriori(basket)

    # Generate rules
    rules = generate_rules(frequent_itemsets)

    print("[TEST] Top 5 rules:")
    print(rules.head())


